# Generated by Django 3.0.6 on 2020-06-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_upload',
            field=models.ImageField(default='Style017-1.jpg', upload_to='static/dam'),
        ),
    ]
