# Generated by Django 3.0.6 on 2020-06-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0002_image_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_upload',
            field=models.ImageField(blank=True, default='Style017-1.jpg', null=True, upload_to='static/dam/images/'),
        ),
    ]
