# Generated by Django 3.0.6 on 2020-06-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0004_auto_20200602_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_upload',
            field=models.ImageField(blank=True, default='Style017-1.jpg', null=True, upload_to='images/'),
        ),
    ]
