# Generated by Django 3.0.6 on 2020-06-03 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('dam', '0005_auto_20200602_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='UserImage',
        ),
    ]
