# Generated by Django 3.0.6 on 2020-06-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0006_auto_20200603_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='thumb_image_upload',
            field=models.ImageField(blank=True, default='Style017-1.jpg', null=True, upload_to='images/'),
        ),
    ]
