# Generated by Django 3.0.6 on 2020-06-02 04:23

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=300)),
                ('image_thumbnail', models.CharField(max_length=300)),
                ('folder', models.CharField(max_length=100)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('file_size', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=300)),
                ('file_extension', models.CharField(max_length=10)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
